We're terribly sorry, but an internal error has occurred :(
This will be written to the console and a file named exception.txt in the current directory.
Press ESCAPE to exit (if displayed on-screen)
Game could not be saved.
NameError: global name 'choice_above' is not defined
Traceback (most recent call last):
  File "/Users/vinyldarkscratch/Dropbox/peltengine/pelt/main.py", line 255, in main
    g.mainloop() #start the main loop
  File "/Users/vinyldarkscratch/Dropbox/peltengine/pelt/main.py", line 210, in mainloop
    surface = self.update_func() #tell current object to update for one frame
  File "/Users/vinyldarkscratch/Dropbox/peltengine/pelt/titlescreen.py", line 147, in update
    self.update_func(self.surf) #call specified update function
  File "/Users/vinyldarkscratch/Dropbox/peltengine/pelt/titlescreen.py", line 136, in main_update
    self.active_menu.update()
  File "/Users/vinyldarkscratch/Dropbox/peltengine/pelt/menu.py", line 191, in update
    choice = self.dlog.update(self.surf, (0, 1)) #draw dialog
  File "/Users/vinyldarkscratch/Dropbox/peltengine/pelt/dialog.py", line 279, in update
    if choice_above: h = self.image.get_height()+50
NameError: global name 'choice_above' is not defined

Error handler finished.
